### PR TITLE
fag_v3 compile error fix on A2

### LINKED ISSUE #245: [BUG]:FAG-V3 compile error on A2
### Preflight checklist

- [x] I have searched the existing issues and confirmed this is not a duplicate.
- [x] I can reproduce this on the latest release.
- [x] I have removed any sensitive information from logs or code snippets.

### Environment

- Device (e.g., Ascend 910B):
- CANN version:9.2.0
- PyTorch version:2.9.0
- torch_npu version:2.9.0
- Python version:3.12.1
- flash_attn_npu version:0.3.0
- etc.

### Bug Description

Compiling A2 code in CANN package 9.2 yields an error:simd_vf function 'MulsMaskSimpleSoftmax' must be a free function or static member function

### Steps to Reproduce

Compile using Cann package 9.2.0:python setup.py install

### Error output

```shell
simd_vf function 'MulsMaskSimpleSoftmax' must be a free function or static member function
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by caihuali373**
## Related Issue

Closes #245 

## Summary

Fix FAG-V3 compilation errors for certain specific cann packages on A2

## Validation

image

### CODE REVIEW

**Comment by jianshuqiang-cpu** [comment]
## NPU CI

- 触发人: @caihuali373
- 模式: `full` (含 Example ST)
- PR: #244  commit: `8b14ec9d`
- 状态: 失败
- Actions: [https://github.com/MinghuasLab/flash-attention-npu/actions/runs/34978643489](https://github.com/MinghuasLab/flash-attention-npu/actions/runs/34978643489)

**Review by YuHao-1010 — APPROVED** [review]
